### PR TITLE
update 'eloquent' to \Awssat\Visits\DataEngines\EloquentEngine::class

### PR DESCRIPTION
**Pull request by remxcode**
As the 'eloquent' engine has been changed to EloquentEngine::class, I updated it universally.

### CODE REVIEW

**Comment by BSN4** [comment]
blank PR with no explanation what is this for ?

**Comment by BSN4** [comment]
this is a major change and would be a breaking change so i'm not sure how we should handle it

**Comment by abdumu** [comment]
@BSN4 I think this related to #95, what do you think ?

**Comment by BSN4** [comment]
@abdumu I like the changes as long we do major release and upgrade note .. its your call friend to merge the PR

**Pull request merged**
