### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:warning: Shift detected GitHub Actions which run jobs using a version `matrix`. Shift attempted to [update your configuration](https://github.com/awssat/laravel-visits/pull/98/commits/a7ecdb0390b0fecc3053ffb117939e079959a4b5?w=1) for Laravel 11. However, you should review these changes to ensure the desired combination of versions are built for your package.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-visits.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "awssat/laravel-visits": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by BSN4** [comment]
Tests failed need more work

**Comment by jasonmccreary** [comment]
My guess is these are dependency/CI related. For example, there isn't a `11.*` constraint for Laravel yet. You would need to target `dev-master` or `^11.0` I believe works for Composer. Also, it's possible the underlying `carbon\carbon` dependency is 3.x on PHP 8.2 causing issues with Laravel 9.

**Comment by Mahan-Shoghy** [comment]
When this will publish?

**Comment by Jerimu** [comment]
any news? This is my only package thats keeping me from upgrading to 11 right now.

**Comment by BSN4** [comment]
> any news? This is my only package thats keeping me from upgrading to 11 right now.

@Jerimu PRs are always welcome

**Comment by syntafin** [comment]
> > any news? This is my only package thats keeping me from upgrading to 11 right now.
> 
> @Jerimu PRs are always welcome

This is a PR for L11 compability

**Comment by BSN4** [comment]
> > > any news? This is my only package thats keeping me from upgrading to 11 right now.
> > 
> > 
> > @Jerimu PRs are always welcome
> 
> This is a PR for L11 compability

yeah but tests are failing sorry I don't have time to fix this PR.

**Comment by abdumu** [comment]
Latest release supports Laravel 11 now.

**Comment by syntafin** [comment]
PR forgot to add Carbon ^3.0 in the depedencies for new created L11 projects - see https://github.com/awssat/laravel-visits/pull/99

**Comment by abdumu** [comment]
Laravel 11 supports both versions 2 and 3.

**Comment by syntafin** [comment]
Yes and new projects comes with 3, as I tried to require 6.1 in a fresh L11 project.

**Pull request closed without merging**
